[package]
name = "poetisa-audio-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
kira = "0.9.6"  # For audio management
fundsp = "0.20.0"
wasm-bindgen = "0.2.95"

[lib]
crate-type = ["cdylib"]
